name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        meteor: [2.7.3, 2.9.1, 2.13.3]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Meteor
        uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: ${{ matrix.meteor }}
      - name: Setup tests
        run: |
          meteor create --release ${{ matrix.meteor }} --bare test
      - name: Test
        working-directory: ./test
        run: METEOR_PACKAGE_DIRS="../" meteor test-packages --once --driver-package meteortesting:mocha ../
